all: App.java BubbleSort.java MP3.java
	javac App.java BubbleSort.java MP3.java

run: all
	java App

clean:
	rm -rf *.class *.zip *.mp3

zip: clean
	zip zip.zip *.java Makefile

newtest:
	printf "fdahfiuadgoiudalidaughbadlkfnadiugba\naflfbaluefaeu" > a-001_a.mp3 && printf "a\n\n" > b-0002_B.mp3 && printf "segundo\n" > c-0921~zika.mp3